version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teamstextify-app
    ports:
      - "3075:3000"
    environment:
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - NODE_ENV=production
    volumes:
      - ./prisma:/app/prisma
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
